apiVersion: v2
name: altinity-clickhouse-operator
description: |-
  Helm chart to deploy [altinity-clickhouse-operator](https://github.com/Altinity/clickhouse-operator).

  The ClickHouse Operator creates, configures and manages ClickHouse clusters running on Kubernetes.

  Refer to operator repo for additional information.
type: application
version: 0.0.4
appVersion: 0.13.0
home: https://github.com/slamdev/helm-charts/tree/master/charts/altinity-clickhouse-operator
icon: https://artifacthub.io/image/2d6aa29c-c74f-4bff-bede-ba7e6e0315a7@2x
maintainers:
  - name: slamdev
    email: valentin.fedoskin@gmail.com
