apiVersion: v2
name: hetzner-irobo
description: |-
  Helm chart to deploy [hetzner-irobo](https://github.com/slamdev/hetzner-irobo).
type: application
version: 0.0.2
appVersion: "0.0.1"
home: https://github.com/slamdev/helm-charts/tree/master/charts/hetzner-irobo
icon: https://i.stack.imgur.com/mwFzF.png
maintainers:
  - name: slamdev
    email: valentin.fedoskin@gmail.com
