apiVersion: v2
name: pgweb
description: |-
  Helm chart to deploy [pgweb](https://hub.docker.com/r/sosedoff/pgweb).
type: application
version: 0.0.5
appVersion: "0.11.7"
home: https://github.com/slamdev/helm-charts/tree/master/charts/pgweb
icon: https://i.stack.imgur.com/mwFzF.png
maintainers:
  - name: slamdev
    email: valentin.fedoskin@gmail.com
