apiVersion: v2
name: octavia-ingress-controller
description: |-
  Helm chart to deploy [octavia-ingress-controller](https://github.com/kubernetes/cloud-provider-openstack/blob/master/docs/octavia-ingress-controller/using-octavia-ingress-controller.md).
type: application
version: 0.0.4
appVersion: "v1.20.0"
home: https://github.com/slamdev/helm-charts/tree/master/charts/octavia-ingress-controller
icon: https://i.stack.imgur.com/mwFzF.png
maintainers:
  - name: slamdev
    email: valentin.fedoskin@gmail.com
