apiVersion: v2
name: external-secrets-operator
description: |-
  Helm chart to deploy [external-secrets-operator](https://github.com/slamdev/external-secrets-operator).

  External Secrets Operator watches changes in external key-value backends to sync them with Kubernetes Secrets and ConfigMaps.

  Refer to operator repo for additional information.
type: application
version: 0.0.13
appVersion: 0.0.6
home: https://github.com/slamdev/helm-charts/tree/master/charts/external-secrets-operator
icon: https://upload.wikimedia.org/wikipedia/commons/thumb/4/48/Emblem-question.svg/1200px-Emblem-question.svg.png
maintainers:
  - name: slamdev
    email: valentin.fedoskin@gmail.com
